# @TODO Not sure if a list of routers is appropriate, since later sections will apply to all of them
# Could limit to one in validation, and leave this format for easy future config translation
routers:
  - name: router01
    # If an interface is not specifically listed here, it will be assumed disabled
    # To properly support this, we may need to do some interface discovery on the routers
    # since we need to have a basic disabled block like:
    # ethernet eth0 {
    #   disable
    #   duplex auto
    #   speed auto
    # }
    interfaces:
      eth0:
        name: LAN_10_100_1_X
        addresses:
          - 10.100.1.1/24
        mtu: 9000
      eth1:
        name: WAN
        addresses:
          - 10.0.0.3/22
          - 2001:db8::/32
        # @TODO ipv6 settings
      eth2:
        name: LAN_10_100_0_X
        addresses:
          - 10.100.0.1/24
        mtu: 9000
    dhcp:
      - name: LAN_10_100_0_X
        authoritative: true
        subnet: 10.100.0.0/24
        router: 10.100.0.1
        start: 10.100.0.150
        stop: 10.100.0.254
        lease: 86400 # @TODO This should be a default if not set
        # @TODO check if 2 is the limit or if non-ui config will issue more
        # Add validation check either way
        dns:
          - 1.1.1.1
          - 8.8.8.8
      - name: LAN_10_100_1_X
        authoritative: true
        subnet: 10.100.1.0/24
        router: 10.100.1.1
        start: 10.100.1.150
        stop: 10.100.1.254
        lease: 86400
        dns:
          - 1.1.1.1
          - 8.8.8.8
    nat:
      # Rule 1
      - name: Simple Port Forward
        type: destination
        inbound_interface: eth1
        protocol: tcp # Optional
        log: false
        outside_address:
          address: 10.0.0.4 # The "public" IP address coming in to the router
          port: 443
        inside_address:
          address: 10.100.1.22
          port: 443
      # Rule 5000
      # Changes the outbound IP to an alternate public IP
      - name: Public IP - Example Host
        type: source
        outbound_interface: eth1
        protocol: all
        log: false
        inside_address:
          address: 10.100.1.22
        outside_address:
          address: 10.0.0.4
      # Rule 5001
      - name: Masquerade for WAN
        type: masquerade
        outbound_interface: eth1
        protocol: all
        log: false
    users:
      - username: ubnt
        # @TODO this should support reading from ENV
        # Also may need a way to change password, while still being able to access the router to do the change
        password: ubnt
        role: admin

#switches:
#  - name: switch01

#firewall:
#  - <rule>

#vlans:
#  -
